In [52]:
import pandas as pd
import numpy as np

df= pd.read_csv("C:\\Users\\bhoom\\Downloads\\test-data.csv")
df

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price
0,0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26 km/kg,998 CC,58.2 bhp,4.0,NaN
1,1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,24.7 kmpl,796 CC,47.3 bhp,5.0,NaN
2,2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,13.68 kmpl,2393 CC,147.8 bhp,7.0,25.27 Lakh
3,3,Toyota Etios Liva GD,Hyderabad,2012,139000,Diesel,Manual,First,23.59 kmpl,1364 CC,null bhp,5.0,NaN
4,4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,18.5 kmpl,1197 CC,82.85 bhp,5.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1229,1229,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN
1230,1230,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN
1231,1231,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN
1232,1232,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN


In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1234 entries, 0 to 1233
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         1234 non-null   int64  
 1   Name               1234 non-null   object 
 2   Location           1234 non-null   object 
 3   Year               1234 non-null   int64  
 4   Kilometers_Driven  1234 non-null   int64  
 5   Fuel_Type          1234 non-null   object 
 6   Transmission       1234 non-null   object 
 7   Owner_Type         1234 non-null   object 
 8   Mileage            1234 non-null   object 
 9   Engine             1224 non-null   object 
 10  Power              1224 non-null   object 
 11  Seats              1223 non-null   float64
 12  New_Price          182 non-null    object 
dtypes: float64(1), int64(3), object(9)
memory usage: 125.5+ KB


In [54]:
df=df.drop("Unnamed: 0", axis = 1)

In [55]:
df.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price'],
      dtype='object')

In [56]:
df.columns.value_counts()

Name                 1
Location             1
Year                 1
Kilometers_Driven    1
Fuel_Type            1
Transmission         1
Owner_Type           1
Mileage              1
Engine               1
Power                1
Seats                1
New_Price            1
Name: count, dtype: int64

In [57]:
df.duplicated().sum()

np.int64(1)

In [58]:
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price
0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26 km/kg,998 CC,58.2 bhp,4.0,NaN
1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,24.7 kmpl,796 CC,47.3 bhp,5.0,NaN
2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,13.68 kmpl,2393 CC,147.8 bhp,7.0,25.27 Lakh
3,Toyota Etios Liva GD,Hyderabad,2012,139000,Diesel,Manual,First,23.59 kmpl,1364 CC,null bhp,5.0,NaN
4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,18.5 kmpl,1197 CC,82.85 bhp,5.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1229,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN
1230,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN
1231,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN
1232,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN


In [59]:
df["New_Price"].isna().sum()

np.int64(1052)

In [60]:
df=df.drop("New_Price",axis=1)

In [61]:
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26 km/kg,998 CC,58.2 bhp,4.0
1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,24.7 kmpl,796 CC,47.3 bhp,5.0
2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,13.68 kmpl,2393 CC,147.8 bhp,7.0
3,Toyota Etios Liva GD,Hyderabad,2012,139000,Diesel,Manual,First,23.59 kmpl,1364 CC,null bhp,5.0
4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,18.5 kmpl,1197 CC,82.85 bhp,5.0
...,...,...,...,...,...,...,...,...,...,...,...
1229,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0
1230,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0
1231,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0
1232,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0


In [62]:
df.isna().sum()

Name                  0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               0
Engine               10
Power                10
Seats                11
dtype: int64

## Name

In [63]:
df["Name"].isna().sum()

np.int64(0)

In [64]:
df["Name"].unique()

array(['Maruti Alto K10 LXI CNG', 'Maruti Alto 800 2016-2019 LXI',
       'Toyota Innova Crysta Touring Sport 2.4 MT',
       'Toyota Etios Liva GD', 'Hyundai i20 Magna',
       'Mahindra XUV500 W8 2WD', 'Toyota Fortuner 4x2 AT TRD Sportivo',
       'Hyundai EON Era Plus', 'Honda City 1.5 S MT',
       'Mahindra XUV500 W6 2WD', 'Audi Q5 2008-2012 2.0 TDI',
       'Hyundai Grand i10 Magna', 'Toyota Corolla H5',
       'Maruti Swift Vdi BSIII', 'Nissan Terrano XL', 'BMW X1 sDrive20d',
       'BMW 3 Series GT 320d Luxury Line', 'Ford Ikon 1.4 TDCi DuraTorq',
       'Maruti Swift AMT ZXI', 'Maruti Swift Dzire VXi',
       'Maruti Ritz LDi', 'Nissan Micra XV',
       'Skoda Laura 1.8 TSI Ambition',
       'Honda Civic 2010-2013 1.8 S MT Inspire', 'Ford Ikon 1.3 Flair',
       'Maruti Alto LX', 'Honda Jazz 1.5 V i DTEC',
       'Skoda Rapid 1.5 TDI AT Ambition', 'Hyundai i20 1.2 Sportz',
       'Toyota Etios Cross 1.4L VD', 'Volkswagen Polo GT TDI',
       'Hyundai i10 Era 1.1 iTech SE', 'Mi

In [65]:
df["Name"].dtypes

dtype('O')

## Location 

In [66]:
df["Location"].isna().sum()

np.int64(0)

In [67]:
df["Location"].unique()

array(['Delhi', 'Coimbatore', 'Mumbai', 'Hyderabad', 'Pune', 'Jaipur',
       'Chennai', 'Kochi', 'Bangalore', 'Kolkata', 'Ahmedabad'],
      dtype=object)

In [68]:
df["Location"].value_counts()

Location
Mumbai        159
Pune          143
Coimbatore    136
Hyderabad     134
Kochi         121
Kolkata       119
Delhi         106
Chennai        97
Jaipur         86
Bangalore      82
Ahmedabad      51
Name: count, dtype: int64

## Year

In [69]:
df["Year"].isna().sum()

np.int64(0)

In [70]:
df["Year"].unique()

array([2014, 2013, 2017, 2012, 2016, 2015, 2011, 2007, 2008, 2009, 2019,
       2010, 2005, 2006, 2018, 2003, 1996, 2004, 2002, 2000])

In [71]:
df["Year"].value_counts()

Year
2015    185
2016    145
2013    142
2014    128
2017    122
2011    113
2012    110
2010     65
2018     63
2009     54
2008     33
2007     23
2019     17
2006     11
2005     11
2004      4
2003      3
2002      3
1996      1
2000      1
Name: count, dtype: int64

In [72]:
df["Year"].dtypes

dtype('int64')

## Kilometers_Driven

In [73]:
df["Kilometers_Driven"].isna().sum()

np.int64(0)

In [74]:
df["Kilometers_Driven"].unique()

array([ 40929,  54493,  34000, 139000,  29000,  85609,  59000,  65000,
        66000,  54684,  78000,  21000,  90000,  87628,  45000,  30788,
        39524, 140000,  15409,  36502, 200000,  70000,  36701,  72000,
        40000,  47000,  93500,  52000,  55429, 133000,  68000,  71000,
       121000, 107000,  51000,  13500,  13000,  81000,  66889,  32000,
        87001,  55000,   4000,  27778,   5000,  59299,  75000,   3413,
        62000, 105001,  89000,  50000,  70687, 104350, 150000,  35223,
        48000,  60000,   7000,  47572,  72727,   4708,  44198,  35000,
        63831,  17540,  14000,  75422,  67000,  79999,   5044,  31601,
        16000,  31700,  76969,  37000,  23000,  59098, 142299,  75731,
        69627,  49000,  25700,  80800, 110896,  62261,  27610,  89219,
         6700,  51599,  37489,  98000,  25183,  52100,  95000,  66346,
        69150,  31000,  63058,  22000,  73026,  21762,  29738,  16053,
        61665,  34820,  12000,  32287, 121134,  74485,  63000,  53190,
      

In [75]:
df["Kilometers_Driven"].dtypes

dtype('int64')

## Fuel_Type

In [76]:
df["Fuel_Type"].isna().sum()

np.int64(0)

In [77]:
df["Fuel_Type"].unique()

array(['CNG', 'Petrol', 'Diesel', 'LPG'], dtype=object)

In [78]:
df["Fuel_Type"].value_counts()

Fuel_Type
Diesel    647
Petrol    579
CNG         6
LPG         2
Name: count, dtype: int64

## Transmission

In [79]:
df["Transmission"].isna().sum()

np.int64(0)

In [80]:
df["Transmission"].unique()

array(['Manual', 'Automatic'], dtype=object)

In [81]:
df["Transmission"].value_counts()

Transmission
Manual       905
Automatic    329
Name: count, dtype: int64

## Owner_Type

In [82]:
df["Owner_Type"].isna().sum()

np.int64(0)

In [83]:
df["Owner_Type"].unique()

array(['First', 'Second', 'Third', 'Fourth & Above'], dtype=object)

In [84]:
df["Owner_Type"].value_counts()

Owner_Type
First             1023
Second             184
Third               24
Fourth & Above       3
Name: count, dtype: int64

## Mileage

In [85]:
df["Mileage"].isna().sum()

np.int64(0)

In [86]:
df["Mileage"].unique()

array(['32.26 km/kg', '24.7 kmpl', '13.68 kmpl', '23.59 kmpl',
       '18.5 kmpl', '16.0 kmpl', '12.55 kmpl', '21.1 kmpl', '17.0 kmpl',
       '15.1 kmpl', '12.8 kmpl', '18.9 kmpl', '13.4 kmpl', '17.8 kmpl',
       '13.24 kmpl', '17.05 kmpl', '19.59 kmpl', '13.8 kmpl', '22.0 kmpl',
       '17.5 kmpl', '23.2 kmpl', '18.06 kmpl', '15.5 kmpl', '19.7 kmpl',
       '27.3 kmpl', '21.66 kmpl', '15.11 kmpl', '19.81 kmpl', '10.5 kmpl',
       '23.4 kmpl', '19.1 kmpl', '14.84 kmpl', '15.29 kmpl', '22.48 kmpl',
       '27.39 kmpl', '17.11 kmpl', '16.55 kmpl', '15.41 kmpl',
       '24.52 kmpl', '20.73 kmpl', '20.0 kmpl', '12.99 kmpl',
       '18.88 kmpl', '22.7 kmpl', '11.4 kmpl', '14.16 kmpl', '17.01 kmpl',
       '24.3 kmpl', '19.09 kmpl', '17.7 kmpl', '14.53 kmpl', '18.6 kmpl',
       '20.14 kmpl', '23.0 kmpl', '18.2 kmpl', '15.4 kmpl', '18.4 kmpl',
       '16.02 kmpl', '0.0 kmpl', '18.16 kmpl', '23.84 kmpl', '23.08 kmpl',
       '18.12 kmpl', '19.16 kmpl', '21.43 kmpl', '22.32 kmpl',
       '2

In [87]:
df["Mileage"].value_counts()

Mileage
17.0 kmpl     35
18.9 kmpl     29
18.6 kmpl     25
21.1 kmpl     20
18.0 kmpl     20
              ..
23.5 kmpl      1
17.19 kmpl     1
21.02 kmpl     1
19.33 kmpl     1
27.28 kmpl     1
Name: count, Length: 301, dtype: int64

In [88]:
df["Mileage"] = df["Mileage"].str.extract(r"(\d+\.?\d*)")[0].astype(float)
df["Mileage_kmpl"] = df["Mileage"] * 1.33

In [89]:
df["Mileage_kmpl"].isna().sum()

np.int64(0)

In [90]:
df["Mileage_kmpl"]=df["Mileage_kmpl"].astype(int)

In [91]:
df["Mileage_kmpl"].dtypes

dtype('int64')

In [92]:
df["Mileage_kmpl"].value_counts()

Mileage_kmpl
25    100
22     98
23     94
24     88
17     86
27     74
26     69
21     62
30     57
28     55
20     54
29     52
19     51
18     41
32     39
15     36
31     32
16     26
33     24
34     21
13     13
0      13
14     11
36      9
37      9
35      8
12      4
11      3
42      3
40      1
10      1
Name: count, dtype: int64

In [94]:
df.drop("Mileage", axis=1, inplace=True)

In [95]:
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Engine,Power,Seats,Mileage_kmpl
0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,998 CC,58.2 bhp,4.0,42
1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,796 CC,47.3 bhp,5.0,32
2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,2393 CC,147.8 bhp,7.0,18
3,Toyota Etios Liva GD,Hyderabad,2012,139000,Diesel,Manual,First,1364 CC,null bhp,5.0,31
4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,1197 CC,82.85 bhp,5.0,24
...,...,...,...,...,...,...,...,...,...,...,...
1229,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,1598 CC,103.6 bhp,5.0,27
1230,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,1197 CC,103.6 bhp,5.0,22
1231,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,1461 CC,63.1 bhp,5.0,30
1232,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,1197 CC,103.6 bhp,5.0,22


## Engine

In [96]:
df["Engine"].isna().sum()

np.int64(10)

In [97]:
df.dropna(subset="Engine", inplace=True)

In [98]:
df["Engine"].isna().sum()

np.int64(0)

In [99]:
df["Engine"].unique()

array(['998 CC', '796 CC', '2393 CC', '1364 CC', '1197 CC', '2179 CC',
       '2982 CC', '814 CC', '1497 CC', '1968 CC', '1794 CC', '1248 CC',
       '1598 CC', '1995 CC', '1399 CC', '1298 CC', '1198 CC', '1799 CC',
       '1299 CC', '1498 CC', '1086 CC', '2835 CC', '1591 CC', '2494 CC',
       '1373 CC', '2143 CC', '2953 CC', '1396 CC', '1798 CC', '1199 CC',
       '1196 CC', '1461 CC', '2487 CC', '1582 CC', '2496 CC', '1368 CC',
       '1596 CC', '1595 CC', '2354 CC', '624 CC', '2993 CC', '936 CC',
       '2987 CC', '1999 CC', '999 CC', '2000 CC', '1493 CC', '1120 CC',
       '3498 CC', '1496 CC', '1405 CC', '1896 CC', '2967 CC', '2477 CC',
       '1948 CC', '1172 CC', '1797 CC', '2498 CC', '1061 CC', '1150 CC',
       '1495 CC', '2499 CC', '1796 CC', '2362 CC', '2523 CC', '5998 CC',
       '2755 CC', '2400 CC', '2349 CC', '995 CC', '1998 CC', '2999 CC',
       '1795 CC', '1984 CC', '793 CC', '1341 CC', '1186 CC', '1499 CC',
       '1991 CC', '799 CC', '1586 CC', '2497 CC', '1956 CC'

In [100]:
df["Engine"] = df["Engine"].str.replace(" CC", "", regex=False).astype(int)

In [101]:
df["Engine"].value_counts()

Engine
1197    126
1248     98
1498     66
1198     54
998      50
       ... 
1948      1
1299      1
5998      1
2362      1
1047      1
Name: count, Length: 104, dtype: int64

In [102]:
df["Engine"].dtypes

dtype('int64')

In [103]:
df.rename(columns={"Engine": "Engine_CC"}, inplace=True)

In [104]:
df.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Engine_CC', 'Power', 'Seats',
       'Mileage_kmpl'],
      dtype='object')

## Power

In [105]:
df["Power"].isna().sum()

np.int64(0)

In [107]:
df["Power"].unique()

array(['58.2 bhp', '47.3 bhp', '147.8 bhp', 'null bhp', '82.85 bhp',
       '140 bhp', '168.7 bhp', '55.2 bhp', '118 bhp', '167.6 bhp',
       '82 bhp', '125 bhp', '75 bhp', '102.5 bhp', '184 bhp', '68 bhp',
       '81.80 bhp', '85.8 bhp', '73.94 bhp', '132 bhp', '70 bhp',
       '46.3 bhp', '98.6 bhp', '103.52 bhp', '80 bhp', '67.06 bhp',
       '103.6 bhp', '68.05 bhp', '107.2 bhp', '74 bhp', '121.3 bhp',
       '102 bhp', '190 bhp', '174.33 bhp', '88.5 bhp', '91.1 bhp',
       '136 bhp', '100.6 bhp', '89.84 bhp', '153.86 bhp', '174.3 bhp',
       '67.04 bhp', '69 bhp', '78 bhp', '138.1 bhp', '81.83 bhp',
       '88.8 bhp', '67 bhp', '82.5 bhp', '120 bhp', '108.62 bhp',
       '67.1 bhp', '86.8 bhp', '93.7 bhp', '62 bhp', '84 bhp', '79.4 bhp',
       '63.1 bhp', '100 bhp', '81.86 bhp', '175.67 bhp', '87.2 bhp',
       '126.32 bhp', '103.2 bhp', '179.5 bhp', '88.76 bhp', '99.6 bhp',
       '120.7 bhp', '62.1 bhp', '83.1 bhp', '180 bhp', '75.94 bhp',
       '126.24 bhp', '35 bhp', '73.

In [117]:
df["Power"] = (
    df["Power"]
    .astype(str)
    .str.extract(r"(\d+\.?\d*)")[0]
    .astype(float)
)

In [118]:
df["Power"].dtypes

dtype('float64')

In [119]:
df["Power"].unique()

array([ 58.,  47., 148.,  nan,  83., 140., 169.,  55., 118., 168.,  82.,
       125.,  75., 102., 184.,  68.,  86.,  74., 132.,  70.,  46.,  99.,
       104.,  80.,  67., 107., 121., 190., 174.,  88.,  91., 136., 101.,
        90., 154.,  69.,  78., 138.,  89., 120., 109.,  87.,  94.,  62.,
        84.,  79.,  63., 100., 176., 126., 103., 180.,  76.,  35., 201.,
       218., 224.,  66., 130., 177., 123., 108., 188., 204., 165., 117.,
       255., 365.,  71., 160., 105.,  85., 203., 247., 110.,  37., 261.,
       271.,  56.,  34., 181., 141., 112., 170., 158., 185., 171., 116.,
        65., 241.,  77., 142.,  64.,  73., 178., 616.,  48., 144.,  92.,
       200., 182., 106., 164., 245., 161.,  98., 127., 114., 208., 258.,
        61., 252., 124.,  53., 150., 152., 210., 172., 215., 143., 191.,
       282., 240., 147., 328., 313., 115., 134.,  54., 198., 362., 450.,
       186., 360., 236., 192., 321., 242.,  93.])

In [123]:
df["Power"].isna().sum()

np.int64(22)

In [124]:
df.dropna(subset="Power", inplace=True)

In [125]:
df["Power"]=df["Power"].astype(int)

In [126]:
df["Power"].dtypes

dtype('int64')

## Seats

In [127]:
df["Seats"].isna().sum()

np.int64(1)

In [128]:
df.dropna(subset="Seats", inplace=True)

In [129]:
df["Seats"].unique()

array([ 4.,  5.,  7.,  6.,  8., 10.,  2.])

In [130]:
df["Seats"].value_counts()

Seats
5.0     1011
7.0      122
8.0       36
4.0       20
6.0        7
10.0       3
2.0        2
Name: count, dtype: int64

In [131]:
df["Seats"]=df["Seats"].astype(int)

In [132]:
df["Seats"].dtypes

dtype('int64')

In [133]:
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Engine_CC,Power,Seats,Mileage_kmpl
0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,998,58,4,42
1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,796,47,5,32
2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,2393,148,7,18
4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,1197,83,5,24
5,Mahindra XUV500 W8 2WD,Coimbatore,2016,85609,Diesel,Manual,Second,2179,140,7,21
...,...,...,...,...,...,...,...,...,...,...,...
1229,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,1598,104,5,27
1230,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,1197,104,5,22
1231,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,1461,63,5,30
1232,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,1197,104,5,22


In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1201 entries, 0 to 1233
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Name               1201 non-null   object
 1   Location           1201 non-null   object
 2   Year               1201 non-null   int64 
 3   Kilometers_Driven  1201 non-null   int64 
 4   Fuel_Type          1201 non-null   object
 5   Transmission       1201 non-null   object
 6   Owner_Type         1201 non-null   object
 7   Engine_CC          1201 non-null   int64 
 8   Power              1201 non-null   int64 
 9   Seats              1201 non-null   int64 
 10  Mileage_kmpl       1201 non-null   int64 
dtypes: int64(6), object(5)
memory usage: 112.6+ KB


In [136]:
df.to_csv("Cars24_Used_car_data.csv", index=False)