In [64]:
# import numpy

import numpy as np

In [65]:
# create 1D array

arr_1d = np.array([1,2,3,4])
arr_1d

array([1, 2, 3, 4])

In [66]:
# 2-D 
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
# 3-D 
arr_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [68]:
# 4_D
arr_4d = np.array([[[[1,23,24,30],[15,16,17,18],[90,91,92,94]]]])
arr_4d

array([[[[ 1, 23, 24, 30],
         [15, 16, 17, 18],
         [90, 91, 92, 94]]]])

In [69]:
arr_1d = np.array([1,2,3,4])
arr_1d

array([1, 2, 3, 4])

In [70]:
# 1d slice: arr[ start : stop : step ]

arr_1d[1:3]

array([2, 3])

In [71]:
# 2d : arr[row_start : row_stop :row_step]

arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,7,6]])
arr_2d[1:,2:]

array([[7, 8],
       [7, 6]])

In [72]:
arr_2d[1:,1:3]

array([[ 6,  7],
       [10,  7]])

In [73]:
arr_3d = np.array([[[1,2,3,4],
                    [3,4,5,6],
                    [5,6,3,4],
                    [4,5,5,6]]])
arr_3d

array([[[1, 2, 3, 4],
        [3, 4, 5, 6],
        [5, 6, 3, 4],
        [4, 5, 5, 6]]])

In [74]:
arr_3d[0,1:,:3]

array([[3, 4, 5],
       [5, 6, 3],
       [4, 5, 5]])

In [75]:
# arr[group,block, row_start: row_end , col_start: col_end]

arr_4d = np.array([[[[1,2,3],
                     [4,5,6],
                     [7,8,9]],
                    [[10,11,12],
                     [13,14,15],
                     [16,17,18]]]])
arr_4d[0,1,1:,1:]

array([[14, 15],
       [17, 18]])

In [77]:
# check di
arr_4d.ndim

4

In [78]:
arr_4d.ndim

4

In [79]:
arr_3d.ndim

3

In [80]:
# array of zeros

arr = np.zeros((2,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [81]:
arr = np.ones((4,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [82]:
# create identity matrix

arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [83]:
# create the range using : arange()

arr_range = np.arange(2,10,2)
arr_range

array([2, 4, 6, 8])

In [84]:
# create the linspace:

line_space = np.linspace(0,1,5)
line_space

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [85]:
# create random array:

array = np.random.rand(3,4)
array

array([[0.93551603, 0.97749334, 0.94730549, 0.60917615],
       [0.23028763, 0.27690352, 0.90678877, 0.41577255],
       [0.0435538 , 0.66219577, 0.32126239, 0.63522151]])

In [86]:
# create random int array:

array = np.random.randint(1,10,(3,4))
array

array([[1, 6, 5, 2],
       [5, 7, 4, 7],
       [4, 7, 6, 7]], dtype=int32)

In [87]:
array = np.random.randint(1,10,(10))
array

array([5, 6, 9, 3, 7, 4, 2, 7, 7, 6], dtype=int32)

In [88]:
np.sort(array)

array([2, 3, 4, 5, 6, 6, 7, 7, 7, 9], dtype=int32)

In [89]:
array.shape

(10,)

In [90]:
array.ndim

1

In [91]:
#
array = np.array([[1,2,3,4],
                  [5,6,7,8]])
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [92]:
array.shape

(2, 4)

In [93]:
array.ndim

2

In [94]:
array.dtype

dtype('int64')

In [95]:
# check the memory of array:

array.nbytes

64

In [96]:
array.size

8

In [97]:
array.itemsize

8

In [98]:
# transpose of array

In [99]:
array.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [100]:
array.shape

(2, 4)

In [101]:
# create complex number:

a = np.array([1+2j,3+4j])
a.real

array([1., 3.])

In [102]:
a.imag

array([2., 4.])

In [103]:
# flat() : converts multi d into into single d: 3x3 into one single line


In [104]:
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [105]:
array.sum(axis = 0) # column sum

array([ 6,  8, 10, 12])

In [106]:
array.sum(axis = 1) # row sum

array([10, 26])

In [107]:
# change the shape : reshape()

a = np.array([1,2,3,4,5,6])

a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [110]:
# 
name = ['Male','Female']

Gender =  np.random.choice(name,10)
Gender

array(['Male', 'Male', 'Female', 'Male', 'Female', 'Male', 'Male', 'Male',
       'Male', 'Female'], dtype='<U6')

In [111]:
# Generate int col

sal = np.random.uniform(10000,25000,10)
sal

array([20824.08729419, 21158.57400669, 13824.21813799, 23310.25077411,
       21985.59718777, 11514.62635457, 16493.68079773, 11907.64037297,
       22917.88985272, 22054.97612205])

In [113]:
# convetring into float val:
np.round(sal,2)

array([20824.09, 21158.57, 13824.22, 23310.25, 21985.6 , 11514.63,
       16493.68, 11907.64, 22917.89, 22054.98])

In [117]:
# class tasks:

# id col : 100
# name col
# gender col
# dept col
# exp col
# role col
# sal col
# size (500 * 7)

import pandas as pd

In [145]:
id = np.arange(100,150)
id.shape

(50,)

In [146]:
name = ["Santosh","Yesh","Sai","Sumit"]
Name = np.random.choice(name,50)
Name.shape

(50,)

In [147]:
g = ["Male","Female"]
Gender = np.random.choice(g,50)
Gender.shape

(50,)

In [148]:
d = ["it","finace","hr","call"]
Dept = np.random.choice(d,50)
Dept.shape

(50,)

In [149]:
exp = np.random.uniform(1,20,50)
exp = np.round(exp,1)
exp.shape

(50,)

In [150]:
role = ["Dev","testing","ai","ds"]
Role = np.random.choice(role,50)
Role.shape

(50,)

In [151]:
s = np.random.uniform(45000,100000,50)
Sal = np.round(s,1)
Sal.shape

(50,)

In [152]:
df = pd.DataFrame({
    "id":id,
    "Name":Name,
    "Gender":Gender,
    "Dept":Dept,
    "exp":exp,
    "Role":Role,
    "Sal":Sal})

In [154]:
df.head()

,id,Name,Gender,Dept,exp,Role,Sal
0,100,Sumit,Male,finace,12.8,ai,68720.1
1,101,Sumit,Male,call,19.7,testing,45079.2
2,102,Sumit,Female,finace,3.2,testing,83595.3
3,103,Santosh,Male,call,7.1,testing,45877.2
4,104,Sumit,Female,call,16.3,testing,69433.4
